stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: printenv
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rdcap-dev/rdcap-jira:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.19.199.13:30003
    env:
    #  PLUGIN_DEBUG: "true"
    # PLUGIN_INSECURE behövs för att komma åt docker registry med self signed cert. 
      PLUGIN_INSECURE: "true"
#- name: Deploy
#  steps:
#  - applyYamlConfig:
#      path: ./deployment.yaml
- name: Publish Helm
  steps:
  - runScriptConfig:
      image: jgreat/rancher-pipeline-publish-chart:0.0.2
      shellScript: publish-chart.sh
    env:
      HELM_REPO_URL: https://10.19.199.13:30003/chartrepo/rdcap-dev/
      CHART_NAME: rdcap-atlassian-jira
      CHART_VERSION: 0.0.${CICD_EXECUTION_SEQUENCE}
    envFrom:
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_PASS
      targetKey: HELM_REPO_PASSWORD
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_USER
      targetKey: HELM_REPO_USERNAME
timeout: 60
notification: {}
