stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: export 
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rdcap-dev/rdcap-jira:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.19.199.13:30003
    env:
      PLUGIN_INSECURE: "true"
- name: Publish Helm
  steps:
  - runScriptConfig:
      image: library/rdcap-rancher-pipeline-publish-chart:latest
      shellScript: |-
       echo $HELM_REPO_CA_CRT >> ca.crt 
       export HELM_REPO_CA_FILE=ca.crt
       chown 10000 ca.crt
       ls -all
       publish-chart.sh 
       ls -all
    env:
      CHART_NAME: rdcap-atlassian-jira
      CHART_VERSION: v0.0.1
      HELM_REPO_INSECURE: "true"
      HELM_REPO_URL: https://10.19.199.13:30003/chartrepo/rdcap-dev/ 
    envFrom:
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_PASS
      targetKey: HELM_REPO_PASSWORD
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_USER
      targetKey: HELM_REPO_USERNAME
    - sourceName: chart-creds
      sourceKey: HELM_REPO_CA_CRT
      targetKey: HELM_REPO_CA_CRT
timeout: 60
notification: {}
