stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: export
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rdcap-dev/rdcap-jira:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor-harbor-registry.harbor.svc.cluster.local:5000
    env:
      PLUGIN_INSECURE: "true"
    envFrom:
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_PASS
      targetKey: DOCKER_PASSWORD
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_USER
      targetKey: DOCKER_USERNAME
- name: Publish Helm
  steps:
  - runScriptConfig:
      image: jgreat/rancher-pipeline-publish-chart:0.0.2
      shellScript: publish-chart.sh
    env:
      CHART_NAME: rdcap-atlassian-jira
      CHART_VERSION: v0.0.1
      HELM_REPO_INSECURE: "true"
      HELM_REPO_URL: http://harbor-harbor-chartmuseum.harbor.svc.cluster.local/rdcap-dev
      PLUGIN_DEBUG: "true"
    envFrom:
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_PASS
      targetKey: HELM_REPO_PASSWORD
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_USER
      targetKey: HELM_REPO_USERNAME
  - applyAppConfig:
      catalogTemplate: cattle-global-data:helm-incubator-chartmuseum
      version: 1.1.1
      name: jira
      targetNamespace: debug
timeout: 60
notification: {}
