stages:
- name: Create Build Tag
  steps:
  - runScriptConfig:
      image: jgreat/drone-build-tag:0.1.0
      shellScript: build-tags.sh --include-feature-tag
    env:
      APPLICATION_VERSION: 1.1.${CICD_EXECUTION_SEQUENCE} 
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile 
      buildContext: .
      tag: rdcap-dev/rdcap-jira:1.1.${CICD_EXECUTION_SEQUENCE} 
#      tag: rdcap-dev/rdcap-jira:use-tags-file
      pushRemote: true
      registry: harbor-harbor-registry.harbor.svc.cluster.local:5000
    env:
      PLUGIN_INSECURE: "true"
      PLUGIN_DEBUG: "true"
    envFrom:
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_PASS
      targetKey: DOCKER_PASSWORD
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_USER
      targetKey: DOCKER_USERNAME
- name: Publish Helm
  steps:
  - runScriptConfig:
      image: jgreat/rancher-pipeline-publish-chart:0.0.2
      shellScript: publish-chart.sh
    env:
      CHART_NAME: rdcap-atlassian-jira
      #CHART_VERSION: v0.0.3
      HELM_REPO_URL: http://harbor-harbor-core.harbor/chartrepo/rdcap-dev/
      PLUGIN_DEBUG: "true"
    envFrom:
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_PASS
      targetKey: HELM_REPO_PASSWORD
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_USER
      targetKey: HELM_REPO_USERNAME
timeout: 60
notification: {}
