stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: printenv
- name: Publish Image
  steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: rdcap-jira:${CICD_EXECUTION_SEQUENCE}
        #pushRemote: true
        registry: docker-registry.docker-registry.10.19.199.2.xip.io
- name: Render and Publish Helm Charts
  steps:
  - runScriptConfig:
      image: jgreat/rancher-pipeline-publish-chart:0.0.2
      shellScript: publish-chart.sh
    env:
      CHART_NAME: rdcap-atlassian-jira-software
      CHART_VERSION: ${CICD_EXECUTION_SEQUENCE}
      HELM_REPO_URL: http://chartmuseum-chartmuseum.chartmuseum.10.19.199.2.xip.io/
#    envFrom:
#    - sourceName: chart-creds
#      sourceKey: BASIC_AUTH_PASS
#      targetKey: HELM_REPO_PASSWORD
#    - sourceName: chart-creds
#      sourceKey: BASIC_AUTH_USER
#      targetKey: HELM_REPO_USERNAME
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
