stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: printenv
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rdcap-jira:${CICD_EXECUTION_SEQUENCE}
      registry: docker-registry.docker-registry.10.19.199.2.xip.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
- name: Publish Helm
  steps:
  - publishCatalogConfig:
      path: charts
      catalogTemplate: atlassian-jira
      version: v0.0.1
      gitUrl: https://github.com/solidparklabs/charts.git
      gitBranch: master
      gitAuthor: Admin
      gitEmail: admin@solidparklab.se
    envFrom:
    - sourceName: github-solidparklab
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: github-solidparklab
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
