stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: printenv
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rdcap-jira:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.19.199.13:30003/rdcap-dev/
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
#- name: Publish Helm
#  steps:
#  - publishCatalogConfig:
#      path: .chart
#      catalogTemplate: atlassian-jira
#      version: v0.0.1
#      gitUrl: git@github.com:solidparklabs/charts.git
#      gitBranch: master
#      gitAuthor: Admin
#      gitEmail: admin@solidparklab.se
#    envFrom:
#    - sourceName: githubchartrepo
#      sourceKey: DEPLOY_KEY
#      targetKey: DEPLOY_KEY
timeout: 60
notification: {}
