kind: Service
apiVersion: v1
metadata:
  name: jira-service
spec:
  selector:
    app: jira-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-test
  labels:
    app: jira-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: jira-app
  template:
    metadata:
      labels:
        app: jira-app
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: jira-app
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
          hostPort: 8080